name: Docker Image CI

on:
  push:
    branches: [ "test" ]


jobs:

  pre-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: scan code for vulnerabilities
        run: |
          echo Downloading cdefense CLI
          echo Downloading cdefense CLI
          curl --location 'https://dev.clouddefenseai.com/api/scan/delta' --header 'clouddefense_api_key: 32762768-54f7-4a53-af05-5bc7835bf9a2' --data '[{"url":"https://github.com/OAndriiovych/delta-scan-demo","type":"GITHUB", "prId":"3"}]'